print ("Masukkan nama : Abel")
print ("Masukkan nomor kursi Abel : 2")
print ("Masukkan nama : Bimo")
print ("Masukkan nomor kursi Bimo : 1")
print ("Masukkan nama : Kiki")
print ("Masukkan nomor kursi Kiki : 2")
print ("Mohon maaf kursi tersebut telah terisi !")
print ("Masukkan nama : Budi")
print ("Masukkan nomor kursi Budi : 3")
print ("Masukkan nama : STOP")

print ("List kursi yang telah terisi :")
print ("Kursi nomor 2 telah diisi oleh Abel")
print ("Kursi nomor 1 telah diisi oleh Bimo")
print ("Kursi nomor 3 telah diisi oleh Budi")
